# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: commerce

services:
  - name: catalog
    project: Catalog/src/Web/Web.csproj
    bindings:
    - name: http
      protocol: http
      port: 5010
    - name: https
      protocol: https
      port: 5011

  - name: portal-web
    project: Portal/src/Web/Web.csproj
    bindings:
    - name: http
      protocol: http
      port: 5000
    - name: https
      protocol: https
      port: 5001

  - name: portal-client
    project: Portal/src/ClientApp/ClientApp.csproj
    bindings:
    - name: http
      protocol: http
      port: 5020
    - name: https
      protocol: https
      port: 5021

      
  - name: orders-web
    project: Orders/src/Web/Web.csproj
    bindings:
    - name: http
      protocol: http
      port: 5040
    - name: https
      protocol: https
      port: 5041

  - name: site
    project: Site/src/Server/Site.Server.csproj
    bindings:
    - name: http
      protocol: http
      port: 6000
    - name: https
      protocol: https
      port: 6001

  - name: mssql
    image: mcr.microsoft.com/azure-sql-edge:latest
    env:
      - name: MSSQL_SA_PASSWORD
        value: P@ssw0rd
      - name: MSSQL_PID
        value: Developer
      - name: ACCEPT_EULA
        value: "Y"
    bindings:
      - port: 1433
        connectionString: Server=${host},${port};User Id=sa;Password=${env:MSSQL_SA_PASSWORD};Encrypt=false
    volumes:
      - source: .data/sql-edge
        target: /var/opt/mssql/data

  - name: rabbitmq
    image: rabbitmq:3-management
    bindings:
      - name: rabbit
        port: 5672
        protocol: rabbitmq
      - name: management
        port: 15672

  - name: zipkin
    image: openzipkin/zipkin
    bindings:
      - port: 9411

  - name: healthchecks
    project: HealthChecks/HealthChecks.csproj
    bindings:
    - name: http
      protocol: http
      port: 5050
    - name: https
      protocol: https
      port: 5051

  - name: identityservice
    project: IdentityService/IdentityService.csproj
    bindings:
    - name: http
      protocol: http
      port: 5030
    - name: https
      protocol: https
      port: 5031

  - name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    args: "azurite-blob --loose --blobHost 0.0.0.0 -l /data"
    bindings:
    - name: blob
      port: 10000
      containerPort: 10000
      protocol: http
    - name: queue
      port: 10001
      containerPort: 10001
      protocol: http
    - name: table
      port: 10002
      containerPort: 10002
      protocol: http
    volumes:
    - source: .data/azurite
      target: /data